#!/usr/bin/env bash
# Displays content of file /etc/passwd showing username, user id, and home directory path for user using while loop
while IFS= read -r line; do
	echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
