#!/usr/bin/env bash
# Displays content of current directory in list format where only the part of the name after the first dash is displayed using for loop and must not display hidden files
list=$(ls)
for i in $list; do
echo "$i" | cut -d '-' -f2
done
